linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true
  govet:
    check-shadowing: true
  gofmt:
    simplify: false
  golint:
    min-confidence: 0
  gocyclo:
    min-complexity: 10
  maligned:
    suggest-new: true
  dupl:
    threshold: 100
  goconst:
    min-len: 3
    min-occurrences: 3
  misspell:
    locale: US
  goimports:
    local-prefixes: github.com/rahul23/trivy

linters:
  disable-all: true
  enable:
    - structcheck
    - ineffassign
    - typecheck
    - govet
    - errcheck
    - varcheck
    - deadcode
    - golint
    - gosec
    - unconvert
    - goconst
    - gocyclo
    - gofmt
    - goimports
    - maligned
    - misspell
    - prealloc

run:
  skip-files:
    - ".*._mock.go$"
    - ".*._test.go$"

issues:
  exclude:
    - "should have a package comment, unless it's in another file for this package"
  exclude-use-default: false
  max-same-issues: 0