defaults: &defaults
  docker :
    - image: knqyf263/ci-trivy:latest
  environment:
    CGO_ENABLED: "1"

jobs:
  release:
    <<: *defaults
    steps:
      - checkout
      - run:
          command: |
            goreleaser --rm-dist

workflows:
  version: 2
  release:
    jobs:  
      - release:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /.*/
