defaults: &defaults
  docker :
      - image: knqyf263/ci-trivy:latest
  environment:
    CGO_ENABLED: "1"

jobs:
  release:
    <<: *defaults
    steps:
      - checkout
      - run:
          command: |
            goreleaser --snapshot --rm-dist --skip-publish

workflows:
  version: 2
  release:
    jobs:  
      - release
