name: Auto-update labels
on:
  push:
    paths:
      - 'misc/triage/labels.yaml'
    branches:
      - main

jobs:
  deploy:
    name: Auto-update labels
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v3.6.0
        with:
          fetch-depth: 0
      - name: Install tools
        uses: aquaproj/aqua-installer@v2.1.2
        with:
          aqua_version: v1.25.0
      - name: update labels
        run: mage label