# This is a manually triggered workflow to build and publish the MkDocs from the
# main branch to GitHub pages at https://aquasecurity.github.io/trivy
name: Deploy documentation

on:
  workflow_dispatch:
    inputs:
      version:
        description: Version to be deployed
        required: true

jobs:
  deploy:
    name: Deploy documentation
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout main
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          persist-credentials: true
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - run: |
          pip install git+https://${GH_TOKEN}@github.com/squidfunk/mkdocs-material-insiders.git
          pip install mike
          pip install mkdocs-macros-plugin
        env:
          GH_TOKEN: ${{ secrets.ORG_GITHUB_TOKEN }}
      - run: |
          git config user.name "knqyf263"
          git config user.email "teppei.fukuda@@aquasec.com"
      - run: |
          mike deploy --push --update-aliases ${{ github.event.inputs.version }} latest
