name: PullRequest title linter
on:
  pull_request:
    types: [edited, opened]
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Go pull request message linter
        uses: masahiro331/go-commitlinter@0.1.1
        env:
          TITLE: ${{ github.event.pull_request.title }}
