name: Publish Chart Helm
on:
  push:
    branches: [main,issue-839-helmRep]
    # paths:
    #   - 'helm/trivy/**'
  workflow_dispatch:
env:
  HELM_REP: helm-charts
  HELM_REP_URL: https://krolval.github.io/helm-charts/
  GH_OWNER: krolval
  CHART_DIR: helm/trivy
  GITHUB_USER: krol3
jobs:
  release:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Install Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.5.0
      - name: Install chart-releaser
        run: |
          wget https://github.com/helm/chart-releaser/releases/download/v1.1.1/chart-releaser_1.1.1_linux_amd64.tar.gz
          tar xzvf chart-releaser_1.1.1_linux_amd64.tar.gz cr
      - name: Package helm chart
        run: |
          ./cr package ${{ env.CHART_DIR }}
      - name: Upload helm chart
        # Failed with upload the same version: https://github.com/helm/chart-releaser/issues/101
        continue-on-error: true
        ## Upload the tar in the Releases repository
        run: |
          ./cr upload -o ${{ env.GH_OWNER }} -r ${{ env.HELM_REP }} --token ${{ secrets.API_TOKEN_GITHUB }} -p .cr-release-packages
      - name: Index helm chart
        run: |
          ./cr index -o ${{ env.GH_OWNER }} -r ${{ env.HELM_REP }} -c ${{ env.HELM_REP_URL }} -i index.yaml
          cp index.yaml /tmp/index.yaml

      - name: Check out chart repo
        uses: actions/checkout@v2
        with:
          repository: ${{ env.GH_OWNER }}/${{ env.HELM_REP }}
          ref: gh-pages
         # token: ${{ secrets.API_TOKEN_GITHUB }}
      - name: Update Helm repository index.yaml
        run: |
          git config --global user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
          cp /tmp/index.yaml ./
          git add index.yaml
          git pull
          git commit -m "Update trivy chart"
          git push origin gh-pages
