name: Release
on:
  push:

env:
  GO_VERSION: "1.16"
  GH_USER: "aqua-bot"
jobs:
  release:
    name: Release
    runs-on: ubuntu-18.04 # 20.04 doesn't provide createrepo for now
    env:
      DOCKER_CLI_EXPERIMENTAL: "enabled"
    steps:
      - name: Install dependencies
        run: |
          sudo apt-get -y update
          sudo apt-get -y install rpm reprepro createrepo distro-info
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - name: Show available Docker Buildx platforms
        run: echo ${{ steps.buildx.outputs.platforms }}
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Cache Go modules
        uses: actions/cache@v2
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Release
        uses: goreleaser/goreleaser-action@v2
        with:
          version: v0.164.0
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.REPO_TOKEN }}
      - name: Checkout trivy-repo
        uses: actions/checkout@v2
        with:
          repository: ${{ github.repository_owner }}/trivy-repo
          path: trivy-repo
          fetch-depth: 0
          token: ${{ secrets.REPO_TOKEN }}
      - name: Setup git settings
        run: |
          git config --global user.email "syedshameersarwar@gmail.com"
          git config --global user.name "syedshameersarwar"
      - name: Import RPM GPG key
        run: echo -e "${{ secrets.RPM_GPG_KEY }}" > private.pgp && echo ${{ secrets.RPM_PASSPHRASE }} | gpg --batch --import private.pgp && rm private.pgp
      - name: Check gpg keys for testing rpm
        run: gpg --list-keys
      - name: Create rpm repository
        env:
          PASSPHRASE: ${{ secrets.RPM_PASSPHRASE }}
        run: ci/deploy-rpm.sh
      - name: Import DEB GPG key
        run: echo -e "${{ secrets.GPG_KEY }}" | gpg --import
      - name: Check gpg keys for testing deb
        run: gpg --list-keys
      - name: Create deb repository
        run: ci/deploy-deb.sh
