name: Test macOS
on:
  push:
    branches:
      - main
    paths-ignore:
      - '*.md'
      - 'docs/**'
      - 'mkdocs.yml'
      - 'LICENSE'
  pull_request:
env:
  GO_VERSION: "1.18"
  TINYGO_VERSION: "0.24.0"
jobs:
  test:
    name: Test - macOS
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Install TinyGo - macOS
        run: |
          brew tap tinygo-org/tools
          brew install tinygo@${TINYGO_VERSION}

      - name: Run unit tests
        run: make test

  module-test:
    name: Module Integration Test - macOS
    runs-on: macos-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ env.GO_VERSION }}
        id: go

      - name: Install TinyGo - macOS
        run: |
          brew tap tinygo-org/tools
          brew install tinygo@${TINYGO_VERSION}

      - name: Checkout
        uses: actions/checkout@v3

      - name: Run module integration tests
        run: |
          make test-module-integration


